[phases.setup]
nixPkgs = ["nodejs-20_x", "yarn"]

[phases.install]
cmds = ["cd ../.. && yarn install --frozen-lockfile && cd apps/backend"]

[phases.build]
cmds = ["npx prisma generate", "yarn build"]

[start]
cmd = "yarn start:prod"
