[phases.setup]
nixPkgs = ["nodejs", "yarn"]

[phases.install]
cmds = [
  "cd ../..",
  "yarn install --frozen-lockfile",
  "cd apps/backend"
]

[phases.build]
cmds = ["npx prisma generate", "yarn build"]

[start]
cmd = "yarn start:prod"
